# NUMPY

In [3]:
import numpy as np              

In [10]:
#tableau a N dimension (ND ARRAY)
#1D ressemble a une liste mais elle plus pluissant et a plus d'attribut scientifique
################## les plus importants a retenir ########################
#constructeur
#np.array / np.zeros / np.random.randn /...

#shape , ndim,size
# Dtype : float16,float64
#manipulation
#concatenate /hstack.vstack/reshape/squeeze/ravel

#########################################################################

import numpy as np

#constructeur de base
A=np.array([1,2,3])
print(A.ndim)
print(A.shape)
#2 attribut a retentir Shape/size
print(A.size)

#constructeur pour initialiser
#initialiser avec des zeros
B=np.zeros((3,2))
print(B)
type(B.shape) # argument doit etre un tuple

#initialiser avec des 1
C=np.ones((3,4))
print(C)
print(C.size)

#initialiser avec une valeur que j'ai choisi
D=np.full( (2,2),9)
print(D)


#module random
type(np.random)
np.random.seed(31)
#generateur de nombre aleatoire
print(np.random.randn(3,4)) #nombre loi normale centre reduite

#matrice identite
np.eye(6)


#sequence de nombre
s=np.linspace(0,10,20) #sample dans R
print(s)

d=np.arange(0,10,1)
print(d) #seq dans R 

#on peut choisir quel type de donne on veut dans notre tableau
np.linspace(0,5,10,dtype=np.float32)


1
(3,)
3
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
12
[[9 9]
 [9 9]]
[[-0.41475721 -0.33336867  0.08109199 -0.79102695]
 [-0.21859967 -0.76319684 -0.77712024  1.84935652]
 [-0.70560031 -0.08604203  0.2879333  -0.13138652]]
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
[0 1 2 3 4 5 6 7 8 9]


array([0.       , 0.5555556, 1.1111112, 1.6666666, 2.2222223, 2.7777777,
       3.3333333, 3.8888888, 4.4444447, 5.       ], dtype=float32)

In [4]:
import numpy as np

b=np.zeros((3,3))
type(b.shape)
b.shape
b.size

np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [5]:
vec=np.array([1,2,3])
print(vec)
print(type(vec))

type(np.arange(0,10))

vec.shape

[1 2 3]
<class 'numpy.ndarray'>


(3,)

In [6]:
#manipulation des tableaux

#coller des tableaux (hstack,vstack) #cbind et Rbind dans R

A=np.ones((2,2))
B=np.eye(2)

c=np.vstack((A,B))
print(c)
D=np.hstack((A,B))
print(D)

#concatenate
np.concatenate((A,B),axis=0)

#methode reshape (changer la forme d'un tableau)

D.size
D=D.reshape((2,4))
D
#squeeze #faire disparaitre 1 dans shape

#methode ravel applatir un tableau a une dimension
#D.ravel()
A=np.array([1,3,4,5])
print(A)
A.shape
A=A.reshape((A.shape[0],1))
print(A.shape)

A=np.ones((2,2))
A=A.ravel()
print(A)

[[1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 1.]]
[[1. 1. 1. 0.]
 [1. 1. 0. 1.]]
[1 3 4 5]
(4, 1)
[1. 1. 1. 1.]


In [18]:
A=np.ones((2,2))
B=np.eye(2)

np.concatenate((A,B),axis=1)

array([[1., 1., 1., 0.],
       [1., 1., 0., 1.]])

In [8]:
#indexing /slicing ?boolean indexing

vec=np.array([1,2,3,4,5])
vec[0]
vec[4]
vec[-1]
vec[0:3]

vec1=np.array([[1,2,3],[4,5,6]])
vec1
vec1[0:2,0:2]

#boolean indexing
ob=np.array([10,15,3,6,1])
#masque
ob>6 #== ; != ; < ; 

Age=np.array([30,21,27,31,56])
Nom=np.array(['lucien','luca','emma','pascale','Anon'])

masque=Age>21
Nom[masque]



array(['lucien', 'emma', 'pascale', 'Anon'], dtype='<U7')

In [9]:
#Indexing
A=np.array([[i for i in range(10)],[i for i in  range(10)]])
print(A)
A[0,0]
A[1,3]

#slicing
#le dernier point n'est jamais prise en compte
A[:,0]
A[0,:] #ou A[0] car c'est l'axe principale

A[0:2,0:2]=10
A[0,:-3]

C=np.zeros((5,5))
print(C)
C[::2,::2]=1
print(C)

#on fait jamais du slicing avec un pas en data science

#boolean indexing
A=np.random.randint(0,10,[5,5])
A<5 #masque
A[A<5]=10


[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]]


In [78]:
#numpy seul qui nous permet de faire ca comme sur R
#liste1=[2,4,4]
#liste1>4

In [10]:
#mathematique et stat avec Numpy
#plus de fonction que le module math
A=np.array([[1,4],[5,9]])
print(A.sum())
print(A.sum(axis=0)) #equivalent de apply
A.mean(axis=1)

#A.cumsum / A.prod / A.cumprod / A.min / A.max /A.argmax / A.sort/ A.argsort

A.argmax(axis=0)
A.var()

print(np.corrcoef(A))

#np.unique
values , count=np.unique(A,return_counts=True) #un peu comme factor
print(count.argsort())
values[count.argsort()]
print(A.cumsum())

19
[ 6 13]
[[1. 1.]
 [1. 1.]]
[0 1 2 3]
[ 1  5 10 19]


In [11]:
#Broadcasting
A=np.ones((2,2))
B=np.ones((2,2))

C=A+B
C=C+3
C

array([[5., 5.],
       [5., 5.]])

In [12]:
#en conclusion

#constructeur ( np.array /np.zeros /np.random.randn)
#manipulation ( A.reshape /A.ravel / A.concatenate)
#methodes utiles ( A.min / A.mean /A.std /A.argmin/...)
#boolean Indexing
#Broadcasting !!!!






In [3]:
vec=np.array([1,3,4,5,6,8])

In [4]:
type(vec)

numpy.ndarray

In [6]:
import numpy as np
mat=np.array([[1,3,4],[3,5,4],[5,7,9]])

In [11]:
mat.sum(axis=0) #colonne

array([ 9, 15, 17])